// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type CreateUserPayload struct {
	User *User `json:"user"`
}

type LoginInput struct {
	Email string `json:"email"`
}

type LoginPayload struct {
	Token string `json:"token"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}
