package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"janjiss.com/rest/graphql/graph/model"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var usersResponse []*model.User
	users, err := r.UserService.GetAllUsers("")

	if err != nil {
		return nil, err
	}

	for _, user := range users {
		usersResponse = append(usersResponse, &model.User{
			ID:    user.ID.String(),
			Email: &user.Email,
		})
	}

	return usersResponse, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
